on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install @craco/craco --save --legacy-peer-deps
          npm install
          npm run build
          
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: eb2a2cebe5a9526e769c6fd63fea0d0a
          projectName: team41robo
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: testversion 
